app/urls.py
# app/urls.py
from django.urls import path

from . import views

app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),
    path('get_xaxis_categories', views.get_xaxis_categories, name='get_xaxis_categories'),
    path('get_yrno_forecast', views.get_yrno_forecast, name='get_yrno_forecast'),
    path('get_ilmateenistus_now', views.get_ilmateenistus_now, name='get_ilmateenistus_now'),
    path('get_aquarea_serv_data', views.get_aquarea_serv_data, name='get_aquarea_serv_data'),
    path('get_ezr_data', views.get_ezr_data, name='get_ezr_data'),
    path('ilm/', views.get_ilmateenistus_now, name='ilm'),
    path('get_aquarea_smrt_data_day', views.get_aquarea_smrt_data_day, name='get_aquarea_smrt_data_day'),
    path('get_aquarea_smrt_data_month', views.get_aquarea_smrt_data_month, name='get_aquarea_smrt_data_month'),
    path('get_aquarea_smrt_data_year', views.get_aquarea_smrt_data_year, name='get_aquarea_smrt_data_year'),
    path('get_tuyaapi_data', views.get_tuyaapi_data, name='get_tuyaapi_data'),
    path('turnon_ledvance', views.turnon_ledvance, name='turnon_ledvance'),
    path('get_nps_12plus12_hours_data', views.get_nps_12plus12_hours_data, name='get_nps_12plus12_hours_data'),
    path('ezr/', views.get_ezr_data, name='ezr'),
    path('yrno/', views.get_yrno_forecast, name='yrno'),
    # path('log/<str:date_string>/', views.log, name='log'),
    # path('status/', views.status, name='status'),
    # path('today/', views.today, name='today'),
    # path('get_weekly_timer/', views.get_weekly_timer, name='get_weekly_timer')
]

dashboard/urls.py
# dashboard/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from app import views as appviews

urlpatterns = [
    path('', appviews.index, name='index'),
    path('app/', include('app.urls')),
    path('chat/', include('chat.urls')),
    path('admin/', admin.site.urls),
]

# Serve static files
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/templates/app/index.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
  <meta HTTP-EQUIV="content-type" CONTENT="text/html; charset=UTF-8" />
  <title>Aquarea Data</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" as="font" crossOrigin="anonymous">

  <link rel="stylesheet" href="{% static 'app/css/base.css' %}" />
  <link rel="stylesheet" href="{% static 'app/css/wind.css' %}" />
  <link rel="stylesheet" href="{% static 'app/css/phenomen.css' %}" />

  <script src="//code.jquery.com/jquery-3.5.1.min.js"></script>
  <!--  https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js-->
  <!--  <script src="https://unpkg.com/axios/dist/axios.min.js"></script>-->
  <script src="https://code.highcharts.com/highcharts.js"></script>
  <script src="https://code.highcharts.com/modules/exporting.js"></script>
  <script src="https://code.highcharts.com/modules/export-data.js"></script>
  <script src="https://code.highcharts.com/modules/accessibility.js"></script>
  <script src="https://code.highcharts.com/modules/pattern-fill.js"></script>
  <script src="https://code.highcharts.com/modules/annotations.js"></script>
</head>
<body>
<div class="chart_wrapper">
  <figure class="highcharts-figure">
    <div id="container"></div>
  </figure>
</div>
<!--Ruumide andmed-->
<div class="wrapper">
  <div id="HeatArea1_t_actual_frame" class="counter col_fourth">
    <img id="img11" width="50" height="50" src="{% static 'app/images/temperature.png' %}" />
    <h1
            id="HeatArea1_t_actual"
            class="timer count-title count-number format_celsius"
    >
      -
    </h1>
     <div class="count-text ">
       <span id="HeatArea1_heatarea_name"></span> <span class="format_target format_celsius" id="HeatArea1_t_target"></span>
     </div>
    <div>
      <input type="range" id="HeatArea1_actor_percent" min="0" max="100" value="10" disabled>
    </div>
  </div>

  <div class="counter col_fourth">
    <img id="img12" width="50" height="50" src="{% static 'app/images/temperature.png' %}" />
    <h1
            id="HeatArea2_t_actual"
            class="timer count-title count-number format_celsius"
    >
      -
    </h1>
    <div class="count-text ">
      <span id="HeatArea2_heatarea_name"></span> <span class="format_target format_celsius" id="HeatArea2_t_target"></span>
    </div>
    <div>
      <input type="range" id="HeatArea2_actor_percent" min="0" max="100" value="10" disabled>
    </div>
  </div>

  <div class="counter col_fourth">
    <img id="img13" width="50" height="50" src="{% static 'app/images/temperature.png' %}" />
    <h1
            id="HeatArea3_t_actual"
            class="timer count-title count-number format_celsius"
    >
      -
    </h1>
    <div class="count-text ">
      <span id="HeatArea3_heatarea_name"></span> <span class="format_target format_celsius" id="HeatArea3_t_target"></span>
    </div>
    <div>
      <input type="range" id="HeatArea3_actor_percent" min="0" max="100" value="10" disabled>
    </div>
  </div>

  <div class="counter col_fourth end">
    <img id="img14" width="50" height="50" src="{% static 'app/images/temperature.png' %}" />
    <h1
            id="HeatArea4_t_actual"
            class="timer count-title count-number format_celsius"
    >
      -
    </h1>
    <div class="count-text ">
      <span id="HeatArea4_heatarea_name"></span> <span class="format_target format_celsius" id="HeatArea4_t_target"></span>
    </div>
    <div>
      <input type="range" id="HeatArea4_actor_percent" min="0" max="100" value="10" disabled>
    </div>
  </div>
</div>

<!--Aquarea andmed-->
<div class="wrapper">
  <div class="counter col_fourth">
    <img id="img23" width="50" height="50" src="{% static 'app/images/icon_tank.png' %}" />
    <div id="img23a" class="fired-ledvance">
      <i width="50" height="50" class="fa fa-plug"></i>
    </div>
    <div id="img23b" class="fired-force-dhw">
      <img width="50" height="50" src="{% static 'app/images/heat_pump.png' %}" />
    </div>

    <h1
            id="tankStatus_temp_now"
            class="timer count-title count-number format_celsius"
    >
      -
    </h1>
    <p class="count-text">
      Tarbevesi <span class="format_target format_celsius" id="tankStatus_temp_target"></span>
    </p>
  </div>

  <div class="counter col_fourth">
    <img id="img24" width="50" height="50" src="{% static 'app/images/heat_pump.png' %}" />
    <h1
            id="olet_water_temp"
            class="timer count-title count-number format_celsius"
    >
      -
    </h1>
    <p class="count-text">
      Akupaagist <span class="format_celsius" id="ilet_water_temp"></span>
    </p>
  </div>

  <div class="counter col_fourth">
    <img id="img21" width="50" height="50" src="{% static 'app/images/heat_pump.png' %}" />
    <h1
            id="z1_water_temp"
            class="timer count-title count-number format_celsius"
    >
      -
    </h1>
     <p class="count-text ">
       2. korrus <span class="format_target format_celsius" id="zone1Status_temp_target"></span>
     </p>
  </div>

  <div class="counter col_fourth end">
    <img id="img22" width="50" height="50"  src="{% static 'app/images/heat_pump.png' %}" />
    <h1
            id="z2_water_temp"
            class="timer count-title count-number format_celsius"
    >
      -
    </h1>
    <p class="count-text ">
      1. korrus <span class="format_target format_celsius" id="zone2Status_temp_target"></span>
    </p>
  </div>
</div>

<!--Ilmaandmed-->
<div class="wrapper">
  <div class="counter col_fourth">
    <img id="img31" width="50" height="50" src="{% static 'app/images/outdoors.png' %}" />
    <h1
            id="act_outd_temp"
            class="timer count-title count-number format_celsius"
    >
      -
    </h1>
    <p class="count-text ">Välisõhk (S9a)</p>
  </div>

  <div class="counter col_fourth">
    <img width="50" height="50" src="{% static 'app/images/outdoors.png' %}" />
    <h1
            id="ilmateenistus_airtemperature"
            class="timer count-title count-number format_celsius"
    >
      -
    </h1>
    <p class="count-text ">Välisõhk (Valga)</p>
  </div>

  <div class="counter col_fourth">
    <span id="ilmateenistusPhenomen" alt="mist" title="mist" class="weather-icon mist"></span>
    <h1
            id="ilmateenistus_relativehumidity"
            class="timer count-title count-number format_percentage"
    >
      -
    </h1>
    <p class="count-text ">Õhuniiskus (Valga)</p>
  </div>

  <div class="counter col_fourth end">
    <span id="ilmateenistusWindOrientation" alt="142 °" title="142 °" class="wind-orientation direction-140"></span>
    <h1

            class="timer count-title count-number"
    >
      <span class="format_speed" id="ilmateenistus_windspeed"></span>
    </h1>
    <p class="count-text ">Tuul <span id="ilmateenistus_winddirection"></span>  (<span class="format_target format_speed" id="ilmateenistus_windspeedmax"></span>)</p>
  </div>
</div>

<!--Tarbimisandmed-->
<div class="wrapper" id="aquarea_consum_table">
  <table class="aquarea_consum_table">
    <thead>
			<tr>
    		<th>Periood</th>
        <th>Kulu (kW/h)</th>
    		<th>Küte (kW/h)</th>
				<th>Vesi (kW/h)</th>
  		</tr>
    </thead>
    <tr>
      <td><span class="text-day">Täna kuni</span> <span class="text-day" id="aquarea_consum_date"></span></td>
      <td><span id="t2na_tot"></span></td>
      <td><span id="t2na_heat"></span></td>
      <td><span id="t2na_tank"></span></td>
    </tr>
    <tr>
      <td><span class="text-day">Eile</span></td>
      <td><span id="eile_tot"></span></td>
      <td><span id="eile_heat"></span></td>
      <td><span id="eile_tank"></span></td>
    </tr>
    <tr>
      <td><span class="text-month">Sel kuul</span></td>
      <td><i class="fa fa-spinner fa-spin spinner-month"></i><span id="kuu_tot"></span></td>
      <td><i class="fa fa-spinner fa-spin spinner-month"></i><span id="kuu_heat"></span></td>
      <td><i class="fa fa-spinner fa-spin spinner-month"></i><span id="kuu_tank"></span></td>
    </tr>
    <tr>
      <td><span class="text-month">Eelmisel kuul</span></td>
      <td><span id="kuu_eelmine_tot"></span></td>
      <td><span id="kuu_eelmine_heat"></span></td>
      <td><span id="kuu_eelmine_tank"></span></td>
    </tr>
    <tr>
      <td><span class="text-month">Eelmise aasta samal kuul</span></td>
      <td><span id="kuu_aasta_tagasi_tot"></span></td>
      <td><span id="kuu_aasta_tagasi_heat"></span></td>
      <td><span id="kuu_aasta_tagasi_tank"></span></td>
    </tr>
    <tr>
      <td><span class="text-year">Sel perioodil (alates 01.07)</span></td>
      <td><i class="fa fa-spinner fa-spin spinner-year"></i><span id="jooksva_perioodi_tot"></span></td>
      <td><i class="fa fa-spinner fa-spin spinner-year"></i><span id="jooksva_perioodi_heat"></span></td>
      <td><i class="fa fa-spinner fa-spin spinner-year"></i><span id="jooksva_perioodi_tank"></span></td>
    </tr>
    <tr>
      <td><span class="text-year">Eelmisel perioodil</span></td>
      <td><span id="eelmise_perioodi_tot"></span></td>
      <td><span id="eelmise_perioodi_heat"></span></td>
      <td><span id="eelmise_perioodi_tank"></span></td>
    </tr>
  </table>
</div>

</body>

{{ chart_24h|json_script:"chart_24h" }}

<script src="{% static 'app/js/app.js' %}"></script>
<script>
$(document).ready(function() {
  const chart_24h_data = JSON.parse(document.getElementById('chart_24h').textContent);
  var chart_24h = Highcharts.chart('container', chart_24h_data);

  const url_get_xaxis_categories = "{% url 'app:get_xaxis_categories' %}";
  update_xaxis_categories(url_get_xaxis_categories, chart_24h);

  const url_get_ezr_data = "{% url 'app:get_ezr_data' %}";
  update_ezr_data(url_get_ezr_data);

  const url_get_ilmateenistus_now = "{% url 'app:get_ilmateenistus_now' %}";
  update_ilmateenistus_now_data(url_get_ilmateenistus_now, chart_24h);

  const url_get_yrno_forecast = "{% url 'app:get_yrno_forecast' %}";
  update_yrno_next12h_data(url_get_yrno_forecast, chart_24h);

  const url_get_tuyaapi_data = "{% url 'app:get_tuyaapi_data' %}";
  update_get_tuyaapi_data(url_get_tuyaapi_data, chart_24h);

  const url_get_aquarea_serv_data = "{% url 'app:get_aquarea_serv_data' %}";
  update_aquarea_serv_data(url_get_aquarea_serv_data, chart_24h);

  const url_get_aquarea_smrt_data_day = "{% url 'app:get_aquarea_smrt_data_day' %}";
  update_aquarea_smrt_data_day(url_get_aquarea_smrt_data_day, chart_24h);

  const url_get_nps_12plus12_hours_data = "{% url 'app:get_nps_12plus12_hours_data' %}";
  update_nps_12plus12_hour_data(url_get_nps_12plus12_hours_data, chart_24h);

  const url_get_aquarea_smrt_data_month = "{% url 'app:get_aquarea_smrt_data_month' %}";
  // update_aquarea_smrt_data_month(url_get_aquarea_smrt_data_month, chart_24h);

  const firedLedvanceDiv = document.getElementById("img23a");
  firedLedvanceDiv.addEventListener("click", (event) => {
    let text = "Lülitame boileri sisse?"
    if (confirm(text) === true) {
      const url_turnon_ledvance = "{% url 'app:turnon_ledvance' %}";
      turnon_ledvance(url_turnon_ledvance, chart_24h);
    }
  })
  firedLedvanceDiv.addEventListener('mouseover',function() {
    const initialOpacity = firedLedvanceDiv.style.opacity;
    if (initialOpacity !== "1") {
      firedLedvanceDiv.style.opacity = "0.2";
      firedLedvanceDiv.addEventListener('mouseleave', function () {
        firedLedvanceDiv.style.opacity = "0";
      }, {once:true})
    }
  })

  const firedForceDHWDiv = document.getElementById("img23b");
  firedForceDHWDiv.addEventListener("click", (event) => {
    let text = "Lülitame tarbevee soojendamise sisse?"
    if (confirm(text) === true) {
      const url_turnon_ledvance = "{% url 'app:turnon_ledvance' %}";
      // turnon_ledvance(url_turnon_ledvance, chart_24h);
    }
  })
  firedForceDHWDiv.addEventListener('mouseover',function() {
    const initialOpacity = firedForceDHWDiv.style.opacity;
    if (initialOpacity !== "1") {
      firedForceDHWDiv.style.opacity = "0.2";
      firedForceDHWDiv.addEventListener('mouseleave', function () {
        firedForceDHWDiv.style.opacity = "0";
      }, {once:true})
    }
  })

  // vajalik, et ära oodata päevaandmete küsimine
  function updateMonth () {
    var el = $('#aquarea_consum_date').text();

    if (el.length) {
      // Do something with el
      update_aquarea_smrt_data_month(url_get_aquarea_smrt_data_month, chart_24h);
    } else {
      setTimeout(updateMonth, 1000); // try again in 1000 milliseconds
    }
  }
  updateMonth();

  const url_get_aquarea_smrt_data_year = "{% url 'app:get_aquarea_smrt_data_year' %}";
  // update_aquarea_smrt_data_year(url_get_aquarea_smrt_data_year, chart_24h);

  // vajalik, et ära oodata kuuandmete küsimine
  function updateYear () {
    var el = $('#kuu_tot').text();

    if (el.length) {
      // Do something with el
      update_aquarea_smrt_data_year(url_get_aquarea_smrt_data_year, chart_24h);
    } else {
      setTimeout(updateYear, 1000); // try again in 1000 milliseconds
    }
  }
  updateYear();
});
</script>

</html>